### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by Marzouq-mohd** [Flutterwave/Flutterwave-Angular-v3#7]
This error shows up each time I add the library to my Ionic Application
![image](https://user-images.githubusercontent.com/31117222/105848309-13d4f000-5fdf-11eb-9c56-8e471c004729.png)

**Comment by tasemgt** [comment]
Same here! Any fix for this yet?

**Comment by greyfinch** [comment]
I am having the same issue. Please, guys quickly fix this.

**Comment by greyfinch** [comment]
So, I found out that this error wasn't related to why my integration didn't work at first, it was me calling a wrong function. My integration to works now, but this  "'removeChild' of null" error is still showing and I know it's caused my flutterwave module because if I remove it the error doesn't show up.

**Comment by toybz** [comment]
Hello guys, apologies for the late response.

Please note that this error message has no effect on your integration or application.
We noticed that the Ionic SDK shows this error when we injected our payment SDK on the page.
As said earlier on though, it has no effect on your app performance or the payment feature.

I will go ahead to close this issue. 
As always, we will be glad to always assist if you encounter any performance or feature issues when using this SDK.
