### ISSUE TITLE
val.replace is not a function

### ISSUE THREAD

**Issue by Olusoladeboy** [Flutterwave/Flutterwave-Angular-v3#8]
I tried testing my flutterwave integration with the test cards, and I keep getting this error 

`"We could not charge this card. Reason: val.replace is not a function".
`
I looked up solutions online, I've passed the amount as a string but this error still persists.

**Comment by toybz** [comment]
Hello Olusoladeboy,
Sincere apologies for the late response,

This is most likely due to the data you have passed to the meta property.
Please ensure that the data in the meta props, only contains basic data type, like string and numbers.
Please see sample below:

meta: {
  customerName: 'Test Name',    **//String, this is okay**
  items: ['test']   **//Array, this wont work**

}

Please let us know if this fixes the issue for you.
